language: c
install: 
  - wget -q -O fb.tar.gz http://downloads.sourceforge.net/fbc/FreeBASIC-0.24.0-linux.tar.gz?download
  - tar zxf fb.tar.gz 
  - cd FreeBASIC-0.24.0-linux 
  - sudo ./install.sh -i
  - cd ..
script: make FBC=/usr/local/bin/fbc && cd tests && make check
branches:
  only:
    - master
compiler:
  - gcc