language: c
install: wget http://downloads.sourceforge.net/fbc/FreeBASIC-0.24.0-linux.tar.gz?download && tar zxf FreeBASIC-0.24.0-linux.tar.gz && cd FreeBASIC-0.24.0-linux && sudo ./install.sh -i
script: make && cd tests && make check
branches:
  only:
    - master
compiler:
  - gcc